name: 'Kraken deploy'
description: 'Create GitHub deployments'
inputs:
  environments:
    description: 'Configuration for the different environments'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/kolonialno/kraken-deploy:main'
  args:
    - ${{ inputs.environments }}
