name: CI

on: push

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.1.12"
  POETRY_HOME: "~/.poetry"

jobs:
  linters:
    name: "${{ matrix.linter }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter: ["isort", "black", "mypy", "flake8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run ${{ matrix.linter }}
        run: make ${{ matrix.linter }}
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup project
        uses: ./.github/actions/setup-project
      - name: Run pytest
        run: pytest -v
